version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8888:8080"
    depends_on:
      - database
      - cache
    networks:
      - app-network

  database:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

  cache:
    build: ./cache
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
